name: Build and push latest

on:
  push:
    branches: [ "master" ]


jobs:

  build-and-push-qwc2-minimal-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push qwc2-minimal-base
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: ghcr.io/${{ github.repository }}-qwc2-minimal-base:latest
        target: qwc2_base
    - name: Build and push qwc2-minimal-dev
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: ghcr.io/${{ github.repository }}-qwc2-minimal-dev:latest
        target: dev
    - name: Build and push qwc2-minimal-builder
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: ghcr.io/${{ github.repository }}-qwc2-minimal-builder:latest
        target: builder
    - name: Build and push qwc2-minimal-prod
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: ghcr.io/${{ github.repository }}-qwc2-minimal-prod:latest
        target: prod
