name: Build and push latest

on:
  push:
    branches: [ "master" ]


jobs:

  build-and-push-qwc2-minimal-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push mgdm2oereb-service
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: ghcr.io/${{ github.repository }}-qwc2-minimal-base:latest
        target: qwc2_base

  build-and-push-qwc2-minimal-dev:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push mgdm2oereb-service
        uses: docker/build-push-action@v3
        with:
          context: ./mgdm2oereb_frontend
          push: true
          tags: ghcr.io/${{ github.repository }}-qwc2-minimal-dev:latest
          target: dev

  build-and-push-qwc2-minimal-builder:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push mgdm2oereb-service
        uses: docker/build-push-action@v3
        with:
          context: ./mgdm2oereb_frontend
          push: true
          tags: ghcr.io/${{ github.repository }}-qwc2-minimal-builder:latest
          target: builder

  build-and-push-qwc2-minimal-prod:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push mgdm2oereb-service
        uses: docker/build-push-action@v3
        with:
          context: ./mgdm2oereb_frontend
          push: true
          tags: ghcr.io/${{ github.repository }}-qwc2-minimal-prod:latest
          target: prod
