name: Build and push tag

on:
  push:
    tags: [ "*" ]


jobs:

  build-and-push-qwc2-minimal-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push qwc2-minimal-base
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}-qwc2-minimal-base:${{ github.ref_name }}
          target: qwc2_base
      - name: Build and push qwc2-minimal-dev
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}-qwc2-minimal-dev:${{ github.ref_name }}
          target: dev
      - name: Build and push qwc2-minimal-builder
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}-qwc2-minimal-builder:${{ github.ref_name }}
          target: builder
      - name: Build and push qwc2-minimal-prod
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}-qwc2-minimal-prod:${{ github.ref_name }}
          target: prod
